### PR TITLE
Create zone_transfer.yaml

### PR DESCRIPTION
**Pull request by frozenfoxx**

### CODE REVIEW

**Review by frozenfoxx — COMMENTED** [review]
Tried moving the @ sign outside of the quotes for the parser.

**Review by frozenfoxx — COMMENTED** [review]
Removed the @ from the function to try to please the parser. User will have to supply that as the first argument.

**Review by frozenfoxx — COMMENTED** [review]
Upon closer inspection the parser really didn't like line 10, not 6, so I've adjusted it to single quotes to try to force YAML to parse correctly.

**Review by frozenfoxx — COMMENTED** [review]
Completely removed the @ sign from the param key list since the parser is extremely angry about it.

**Review by stackrip — APPROVED** [review]
Perfect. Thanks!!! :heart:

**Pull request merged**
